### ISSUE TITLE
Latest build still buggy.

### ISSUE THREAD

**Issue by Unleashed2k** [rscustom/rocksmith-custom-song-toolkit#208]
I'm still having issues with the latest build.

2015-03-03 08:59:50.3803 | RocksmithToolkitGUI.Program (ERROR) : 
 RocksmithToolkitGUI.Program.<Main>b__1 
 
RocksmithToolkitGUI
RocksmithToolkitLib.GameVersion get_CurrentGameVersion()
Exception catched:

 
System.Exception No game version selected. RocksmithToolkitLib.GameVersion get_CurrentGameVersion()    at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.get_CurrentGameVersion() in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 49
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.PopulateAppIdCombo() in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 1655
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.GameVersion_CheckedChanged(Object sender, EventArgs e) in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 1612
   at System.Windows.Forms.RadioButton.OnCheckedChanged(EventArgs e)
   at System.Windows.Forms.RadioButton.set_Checked(Boolean value)
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.FillPackageCreatorForm(DLCPackageData info, String filesBaseDir) in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 852
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.loadTemplate(String dlcLoadPath) in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 579
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.dlcLoadButton_Click(Object sender, EventArgs e) in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 560
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) System.Exception: No game version selected.
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.get_CurrentGameVersion() in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 49
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.PopulateAppIdCombo() in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 1655
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.GameVersion_CheckedChanged(Object sender, EventArgs e) in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 1612
   at System.Windows.Forms.RadioButton.OnCheckedChanged(EventArgs e)
   at System.Windows.Forms.RadioButton.set_Checked(Boolean value)
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.FillPackageCreatorForm(DLCPackageData info, String filesBaseDir) in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 852
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.loadTemplate(String dlcLoadPath) in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 579
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.dlcLoadButton_Click(Object sender, EventArgs e) in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 560
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
2015-03-03 09:00:09.1254 | RocksmithToolkitGUI.Program (ERROR) : 
 RocksmithToolkitGUI.Program.<Main>b__1 
 
RocksmithToolkitGUI
RocksmithToolkitLib.GameVersion get_CurrentGameVersion()
Exception catched:

 
System.Exception No game version selected. RocksmithToolkitLib.GameVersion get_CurrentGameVersion()    at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.get_CurrentGameVersion() in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 49
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.PopulateAppIdCombo() in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 1655
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.GameVersion_CheckedChanged(Object sender, EventArgs e) in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 1612
   at System.Windows.Forms.RadioButton.OnCheckedChanged(EventArgs e)
   at System.Windows.Forms.RadioButton.set_Checked(Boolean value)
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.FillPackageCreatorForm(DLCPackageData info, String filesBaseDir) in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 852
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.loadTemplate(String dlcLoadPath) in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 579
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.dlcLoadButton_Click(Object sender, EventArgs e) in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 560
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) System.Exception: No game version selected.
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.get_CurrentGameVersion() in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 49
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.PopulateAppIdCombo() in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 1655
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.GameVersion_CheckedChanged(Object sender, EventArgs e) in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 1612
   at System.Windows.Forms.RadioButton.OnCheckedChanged(EventArgs e)
   at System.Windows.Forms.RadioButton.set_Checked(Boolean value)
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.FillPackageCreatorForm(DLCPackageData info, String filesBaseDir) in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 852
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.loadTemplate(String dlcLoadPath) in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 579
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.dlcLoadButton_Click(Object sender, EventArgs e) in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 560
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
2015-03-03 09:01:02.7014 | RocksmithToolkitGUI.Program (ERROR) : 
 RocksmithToolkitGUI.Program.<Main>b__1 
 
RocksmithToolkitGUI
RocksmithToolkitLib.GameVersion get_CurrentGameVersion()
Exception catched:

 
System.Exception No game version selected. RocksmithToolkitLib.GameVersion get_CurrentGameVersion()    at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.get_CurrentGameVersion() in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 49
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.get_CurrentRocksmithTitle() in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 124
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.dlcLoadButton_Click(Object sender, EventArgs e) in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 554
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) System.Exception: No game version selected.
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.get_CurrentGameVersion() in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 49
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.get_CurrentRocksmithTitle() in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 124
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.dlcLoadButton_Click(Object sender, EventArgs e) in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 554
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

I'm trying to import: 
https://www.dropbox.com/s/y3wk2khexutivdr/Seether_Nobody-Praying-For-Me_RS2014.dlc.xml?dl=0

Also when importing other songs (example):
https://www.dropbox.com/s/15ebv6y7pj7zdv3/Seether_Goodbye-Tonight_RS2014.dlc.xml?dl=0

It auto goes to convert up top, which breaks tones. You'll have to switch to Rocksmith 2014 which wipes all tones out until reimport. It also removes anything in the wwise field.

Multiple users are experiencing this issue.

**Comment by cozy1** [comment]
Goodbye Tonight is loading in the latest build.  Nobody Praying For Me is broken (No game version selected error).  Try to recreate dlc.xml again.  PM me at CF if you still have trouble.
