### ISSUE TITLE
Thread Exception Cached.... NEED HELP PLEASSSSE!!!!

### ISSUE THREAD

**Issue by choialbert1** [rscustom/rocksmith-custom-song-toolkit#223]
So, today I was about creating a new CDLC... but, today, this error in the attachment popped up when I tried to create a .psarc file for the new dlc. I have already created the base of it using EOF and Guitar Pro. This was the final step!! Is there anything I could try? I do have the .cache folder somewhere and I have tried putting it by coping and pasting it every place that related with the tool kit and EOF... (at least that's what I assume.) I also do have the smashing pumpking cherub rock dlc to change the dlc code but the error keeps popping up!! Please help me!!!
![capture](https://cloud.githubusercontent.com/assets/12401453/7575536/886964ae-f803-11e4-989f-8e5f93360693.PNG)

Rocksmith Custom Song Toolkit log...

__________________________________________________________________________________________________________________________________________________________________

2015-05-12 16:06:51.9161 | RocksmithToolkitGUI.Program (INFO) : 
 RocksmithToolkitGUI.Program.Main 
 Version: 2.6.1.0-5f9b28b6
 OS: Microsoft Windows NT 6.2.9200.0
 Command: "C:\Users\Albert\Desktop\Customs Forge CDLC\Custom Song Tool Kit\RocksmithToolkitGUI.exe"  

2015-05-12 16:13:02.2959 | RocksmithToolkitGUI.Program (ERROR) : 
 RocksmithToolkitGUI.Program.<Main>b__1 
 
RocksmithToolkitLib
Void Convert2Wem(System.String, System.String, Int32)
Exception catched:

 
System.Exception Wwise audio file conversion failed: Could not find Wwise template .cache Windows SFX directory Void Convert2Wem(System.String, System.String, Int32)    at RocksmithToolkitLib.Ogg.Wwise.Convert2Wem(String sourcePath, String destinationPath, Int32 audioQuality) in c:\projects\rocksmith-custom-song-toolkit\RocksmithToolkitLib\Ogg\Wwise.cs:line 24
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.GetPackageData() in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 1286
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.dlcGenerateButton_Click(Object sender, EventArgs e) in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 357
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) System.Exception: Wwise audio file conversion failed: Could not find Wwise template .cache Windows SFX directory
   at RocksmithToolkitLib.Ogg.Wwise.Convert2Wem(String sourcePath, String destinationPath, Int32 audioQuality) in c:\projects\rocksmith-custom-song-toolkit\RocksmithToolkitLib\Ogg\Wwise.cs:line 24
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.GetPackageData() in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 1286
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.dlcGenerateButton_Click(Object sender, EventArgs e) in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 357
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
2015-05-12 16:16:32.1082 | RocksmithToolkitGUI.Program (ERROR) : 
 RocksmithToolkitGUI.Program.<Main>b__1 
 
RocksmithToolkitLib
Void Convert2Wem(System.String, System.String, Int32)
Exception catched:

 
System.Exception Wwise audio file conversion failed: Could not find Wwise template .cache Windows SFX directory Void Convert2Wem(System.String, System.String, Int32)    at RocksmithToolkitLib.Ogg.Wwise.Convert2Wem(String sourcePath, String destinationPath, Int32 audioQuality) in c:\projects\rocksmith-custom-song-toolkit\RocksmithToolkitLib\Ogg\Wwise.cs:line 24
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.GetPackageData() in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 1286
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.dlcGenerateButton_Click(Object sender, EventArgs e) in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 357
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) System.Exception: Wwise audio file conversion failed: Could not find Wwise template .cache Windows SFX directory
   at RocksmithToolkitLib.Ogg.Wwise.Convert2Wem(String sourcePath, String destinationPath, Int32 audioQuality) in c:\projects\rocksmith-custom-song-toolkit\RocksmithToolkitLib\Ogg\Wwise.cs:line 24
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.GetPackageData() in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 1286
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.dlcGenerateButton_Click(Object sender, EventArgs e) in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 357
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
2015-05-12 16:16:57.4098 | RocksmithToolkitGUI.Program (ERROR) : 
 RocksmithToolkitGUI.Program.<Main>b__1 
 
RocksmithToolkitLib
Void Convert2Wem(System.String, System.String, Int32)
Exception catched:

 
System.Exception Wwise audio file conversion failed: Could not find Wwise template .cache Windows SFX directory Void Convert2Wem(System.String, System.String, Int32)    at RocksmithToolkitLib.Ogg.Wwise.Convert2Wem(String sourcePath, String destinationPath, Int32 audioQuality) in c:\projects\rocksmith-custom-song-toolkit\RocksmithToolkitLib\Ogg\Wwise.cs:line 24
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.GetPackageData() in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 1286
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.dlcGenerateButton_Click(Object sender, EventArgs e) in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 357
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) System.Exception: Wwise audio file conversion failed: Could not find Wwise template .cache Windows SFX directory
   at RocksmithToolkitLib.Ogg.Wwise.Convert2Wem(String sourcePath, String destinationPath, Int32 audioQuality) in c:\projects\rocksmith-custom-song-toolkit\RocksmithToolkitLib\Ogg\Wwise.cs:line 24
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.GetPackageData() in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 1286
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.dlcGenerateButton_Click(Object sender, EventArgs e) in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 357
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
2015-05-12 16:17:32.8175 | RocksmithToolkitGUI.Program (ERROR) : 
 RocksmithToolkitGUI.Program.<Main>b__1 
 
RocksmithToolkitLib
Void Convert2Wem(System.String, System.String, Int32)
Exception catched:

 
System.Exception Wwise audio file conversion failed: Could not find Wwise template .cache Windows SFX directory Void Convert2Wem(System.String, System.String, Int32)    at RocksmithToolkitLib.Ogg.Wwise.Convert2Wem(String sourcePath, String destinationPath, Int32 audioQuality) in c:\projects\rocksmith-custom-song-toolkit\RocksmithToolkitLib\Ogg\Wwise.cs:line 24
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.GetPackageData() in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 1286
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.dlcGenerateButton_Click(Object sender, EventArgs e) in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 357
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) System.Exception: Wwise audio file conversion failed: Could not find Wwise template .cache Windows SFX directory
   at RocksmithToolkitLib.Ogg.Wwise.Convert2Wem(String sourcePath, String destinationPath, Int32 audioQuality) in c:\projects\rocksmith-custom-song-toolkit\RocksmithToolkitLib\Ogg\Wwise.cs:line 24
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.GetPackageData() in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 1286
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.dlcGenerateButton_Click(Object sender, EventArgs e) in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 357
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

__________________________________________________________________________________________________________________________________________________________________

Should I also try downgrading the program??

**Comment by cozy1** [comment]
Go to the "Configuration" toolbar at top.  Look at WwiseCLI.exe path and make sure you have entered the correct path to your Wwise configuration.  Confirm that you have Wwise v2013.2x build 48xx series of Wwise installed.  Should fix the problem for you.

**Comment by L0FKA** [comment]
I think vve need to vvrite logic that vvill deal vvith vvise paths and trouvv errors in our face if you've got no vvise :)

**Comment by cozy1** [comment]
Very time consuming to programatically parse entire HD for Wwise install, has been tried.  Many users are doing custom installs of Wwise so it falls back on them to set the correct path.  If you have an idea give it a try.

**Comment by ray** [comment]
You wouldn't need to scan the disk to find the install, either just check the registry (HKLM\SOFTWARE\Audiokinetic Inc.\Wwise\[version]\InstallLocation) or use the environment variable %WWISEROOT% which should point to the last version installed.

**Comment by cozy1** [comment]
Good point.  Could you show me how to use %WWISEROOT%  Thanks

**Comment by ray** [comment]
`Environment.GetEnvironmentVariable("WWISEROOT")` should work

**Comment by cozy1** [comment]
You are very wise.  That works.  I will implement fix.

**Comment by cozy1** [comment]
Added fix for OGG/WAV to WEM audio converter to check for proper Wwise installation (provides better feedback for user).  Thanks to ray for implementation suggestion.  https://github.com/rscustom/rocksmith-custom-song-toolkit/commit/8e8a055ff17c5f27d7e4c1fdfc9c1e2c8da7e049

**Comment by choialbert1** [comment]
Thanks all for the replies... but, I just decided to downgrade it since it was afterall a beta version... It worked perfectly... thanks though.
