### ISSUE TITLE
Index out of Range Converting RS1 to RS2

### ISSUE THREAD

**Issue by Jorgixhallo** [rscustom/rocksmith-custom-song-toolkit#229]
RocksmithToolkitGUI.Program.<Main>b__1 
 
RocksmithToolkitLib
RocksmithToolkitLib.Xml.Song2014 ConvertChordTemplates(RocksmithToolkitLib.Xml.Song, RocksmithToolkitLib.Xml.Song2014)
Exception catched:

 
System.IndexOutOfRangeException Index was outside the bounds of the array. RocksmithToolkitLib.Xml.Song2014 ConvertChordTemplates(RocksmithToolkitLib.Xml.Song, RocksmithToolkitLib.Xml.Song2014)    at RocksmithToolkitLib.Song2014ToTab.Rs1Converter.ConvertChordTemplates(Song rsSong, Song2014 rsSong2014)
   at RocksmithToolkitLib.Song2014ToTab.Rs1Converter.SongToSong2014(Song rsSong)
   at RocksmithToolkitLib.DLCPackage.DLCPackageData.RS1LoadFromFolder(String unpackedDir, Platform targetPlatform, Boolean convert)
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.dlcImportButton_Click(Object sender, EventArgs e) in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 736
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at RocksmithToolkitLib.Song2014ToTab.Rs1Converter.ConvertChordTemplates(Song rsSong, Song2014 rsSong2014)
   at RocksmithToolkitLib.Song2014ToTab.Rs1Converter.SongToSong2014(Song rsSong)
   at RocksmithToolkitLib.DLCPackage.DLCPackageData.RS1LoadFromFolder(String unpackedDir, Platform targetPlatform, Boolean convert)
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.dlcImportButton_Click(Object sender, EventArgs e) in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 736
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Jorgixhallo** [comment]
If needed I can provide the .dat file

**Comment by L0FKA** [comment]
What a truncated log, missing toolkit version and system info(it's impotant to know), and if it's only that dat, then attach it please.

**Comment by Jorgixhallo** [comment]
Full error log:
http://www.filedropper.com/rstoolkit2015-07-18
(there are two other errors, which I manage to solve by unpacking and packing fixing what the error said)
.dat that made the error:
http://www.filedropper.com/rs001song0000034

**Comment by Jorgixhallo** [comment]
PS: What do you guys think about adding a "Report Error" Menu on the interface?

**Comment by cozy1** [comment]
If you post link to dat file on Google or Dropbox I will take a look.

**Comment by L0FKA** [comment]
@cozy1, he showed me rs1 dlc file 34 and 39 you have it i know :)

**Comment by cozy1** [comment]
Fixed RS1->RS2 index out of range exception
Fixed RS1->RS2 tone bug (using key instead of name)
Tested and working

https://github.com/rscustom/rocksmith-custom-song-toolkit/commit/15e1a637af05b1b1568f8d2e89c0c2812c1d6c77
