### ISSUE TITLE
NullReferenceException in WriteXmlComments when generating

### ISSUE THREAD

**Issue by apaatsio** [rscustom/rocksmith-custom-song-toolkit#234]
I'm getting an error when generating a new psarc file for Volbeat - Radio Girl. This error hasn't occurred with other song files. I have tried this with five different files.

Steps to reproduce:

1. Download [Volbeat - Radio Girl from customsforge](http://customsforge.com/page/customsforge_rs_2014_cdlc.html/_/pc-enabled-rs-2014-cdlc/radio-girl-r15885)
2. Start the Custom song toolkit app
3. Click Import and select the Volbeat song
4. Click Generate

Observed result: Error window shows up (see error log at the bottom)
Expected result: A psarc file is generated without errors.

Using build 0b75eabf21 (2015-07-27 19:39:15)

```
2015-08-06 18:02:21.3972 | RocksmithToolkitGUI.Program (INFO) : 
 RocksmithToolkitGUI.Program.Main 
 Version: 2.6.1.0-0b75eabf
 OS: Microsoft Windows NT 6.1.7601 Service Pack 1
 Command: "C:\Users\Antti\Downloads\Rocksmith Tools\RocksmithToolkitGUI.exe" Runtime Version: v4.0.30319.34209JIT: MsX86 

2015-08-06 18:03:05.0589 | RocksmithToolkitGUI.Program (ERROR) : 
 RocksmithToolkitGUI.Program.<Main>b__1 
 
RocksmithToolkitLib
Void WriteXmlComments(System.String, System.Collections.Generic.IEnumerable`1[System.Xml.Linq.XComment])
Exception catched:

 
System.NullReferenceException Object reference not set to an instance of an object. Void WriteXmlComments(System.String, System.Collections.Generic.IEnumerable`1[System.Xml.Linq.XComment])    at RocksmithToolkitLib.Xml.Song2014.WriteXmlComments(String xmlSongRS2014File, IEnumerable`1 commentNodes)
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.dlcGenerateButton_Click(Object sender, EventArgs e) in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 422
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) System.NullReferenceException: Object reference not set to an instance of an object.
   at RocksmithToolkitLib.Xml.Song2014.WriteXmlComments(String xmlSongRS2014File, IEnumerable`1 commentNodes)
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.dlcGenerateButton_Click(Object sender, EventArgs e) in c:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 422
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by apaatsio** [comment]
I tried with previous builds. This works with 8f6178fa32 but not anymore in 84f9df1c0b.

So, **it looks like this bug was introduced in 84f9df1c0b**

**Comment by L0FKA** [comment]
Thanks for the good bugreport, I've got this issue reported already, but with no analysis on it, as temp workaround you can add one empty xml coment to root node or just resave in eof to get it's done automatically.

Working on a hotfix now.
