### ISSUE TITLE
Noob error on Generate

### ISSUE THREAD

**Issue by bacohen8** [rscustom/rocksmith-custom-song-toolkit#287]
2017-05-06 13:54:58.0956 | RocksmithToolkitGUI.Program (INFO) : 
 RocksmithToolkitGUI.Program.Main 
 Version: 2.8.0.0-3d133c61 (32 bit)
 OS: Microsoft Windows NT 6.2.9200.0 (64 bit)
 Runtime: v4.0.30319.42000
 JIT: MsX86 

2017-05-06 13:56:35.1321 | RocksmithToolkitGUI.Program (ERROR) : 
 RocksmithToolkitGUI.Program+<>c.<Main>b__1_1 
 
System
Boolean StartWithShellExecuteEx(System.Diagnostics.ProcessStartInfo)
Exception catched:

 
System.ComponentModel.Win32Exception The operation was canceled by the user Boolean StartWithShellExecuteEx(System.Diagnostics.ProcessStartInfo)    at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at RocksmithToolkitLib.Extensions.GeneralExtensions.RunExternalExecutable(String exeFileName, Boolean toolkitRootFolder, Boolean runInBackground, Boolean waitToFinish, String arguments)
   at RocksmithToolkitGUI.UpdateForm.installButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) System.ComponentModel.Win32Exception (0x80004005): The operation was canceled by the user
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at RocksmithToolkitLib.Extensions.GeneralExtensions.RunExternalExecutable(String exeFileName, Boolean toolkitRootFolder, Boolean runInBackground, Boolean waitToFinish, String arguments)
   at RocksmithToolkitGUI.UpdateForm.installButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
2017-05-06 14:44:20.1705 | RocksmithToolkitGUI.Program (ERROR) : 
 RocksmithToolkitGUI.Program+<>c.<Main>b__1_1 
 
RocksmithToolkitLib
Void Convert2Wem(System.String, System.String, Int32)
Exception catched:

 
System.Exception Wwise audio file conversion failed: You have no compatible version of Audiokinetic Wwise installed.
Install Wwise v2013.2.x or v2014.1.x or even v2015.1.x series if you would like to use
 the toolkit OGG/WAV audio to Wwise WEM audio auto convert features. Void Convert2Wem(System.String, System.String, Int32)    at RocksmithToolkitLib.Ogg.Wwise.Convert2Wem(String wavSourcePath, String destinationPath, Int32 audioQuality)
   at RocksmithToolkitLib.Ogg.OggFile.Convert2Wem(String audioPath, Int32 audioQuality, Int64 previewLength, Int64 chorusTime)
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.GetPackageData()
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.dlcGenerateButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) System.Exception: Wwise audio file conversion failed: You have no compatible version of Audiokinetic Wwise installed.
Install Wwise v2013.2.x or v2014.1.x or even v2015.1.x series if you would like to use
 the toolkit OGG/WAV audio to Wwise WEM audio auto convert features.
   at RocksmithToolkitLib.Ogg.Wwise.Convert2Wem(String wavSourcePath, String destinationPath, Int32 audioQuality)
   at RocksmithToolkitLib.Ogg.OggFile.Convert2Wem(String audioPath, Int32 audioQuality, Int64 previewLength, Int64 chorusTime)
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.GetPackageData()
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.dlcGenerateButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
2017-05-06 14:45:22.7933 | RocksmithToolkitGUI.Program (ERROR) : 
 RocksmithToolkitGUI.Program+<>c.<Main>b__1_1 
 
RocksmithToolkitLib
Void Convert2Wem(System.String, System.String, Int32)
Exception catched:

 
System.Exception Wwise audio file conversion failed: You have no compatible version of Audiokinetic Wwise installed.
Install Wwise v2013.2.x or v2014.1.x or even v2015.1.x series if you would like to use
 the toolkit OGG/WAV audio to Wwise WEM audio auto convert features. Void Convert2Wem(System.String, System.String, Int32)    at RocksmithToolkitLib.Ogg.Wwise.Convert2Wem(String wavSourcePath, String destinationPath, Int32 audioQuality)
   at RocksmithToolkitLib.Ogg.OggFile.Convert2Wem(String audioPath, Int32 audioQuality, Int64 previewLength, Int64 chorusTime)
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.GetPackageData()
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.dlcGenerateButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) System.Exception: Wwise audio file conversion failed: You have no compatible version of Audiokinetic Wwise installed.
Install Wwise v2013.2.x or v2014.1.x or even v2015.1.x series if you would like to use
 the toolkit OGG/WAV audio to Wwise WEM audio auto convert features.
   at RocksmithToolkitLib.Ogg.Wwise.Convert2Wem(String wavSourcePath, String destinationPath, Int32 audioQuality)
   at RocksmithToolkitLib.Ogg.OggFile.Convert2Wem(String audioPath, Int32 audioQuality, Int64 previewLength, Int64 chorusTime)
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.GetPackageData()
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.dlcGenerateButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by bacohen8** [comment]
I think this is resolved by downgrading the W Wise

**Comment by L0FKA** [comment]
Clever one, yes it's because wwise missing or wrong version installed. GJ
