### ISSUE TITLE
Another Noob error- System.ArgumentOutOfRangeException: Value of '-2147483648' is not valid for 'Value'. 'Value' should be between 'minimum' and 'maximum'.

### ISSUE THREAD

**Issue by bacohen8** [rscustom/rocksmith-custom-song-toolkit#288]
2017-05-09 09:50:11.3544 | RocksmithToolkitGUI.Program (INFO) : 
 RocksmithToolkitGUI.Program.Main 
 Version: 2.8.0.0-3d133c61 (32 bit)
 OS: Microsoft Windows NT 6.2.9200.0 (64 bit)
 Runtime: v4.0.30319.42000
 JIT: MsX86 

2017-05-09 10:04:49.3185 | RocksmithToolkitGUI.Program (ERROR) : 
 RocksmithToolkitGUI.Program+<>c.<Main>b__1_1 
 
System.Windows.Forms
Void set_Value(Int32)
Exception catched:

 
System.ArgumentOutOfRangeException Value of '-2147483648' is not valid for 'Value'. 'Value' should be between 'minimum' and 'maximum'.
Parameter name: Value Void set_Value(Int32)    at System.Windows.Forms.ProgressBar.set_Value(Int32 value)
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.dlcGenerateButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) System.ArgumentOutOfRangeException: Value of '-2147483648' is not valid for 'Value'. 'Value' should be between 'minimum' and 'maximum'.
Parameter name: Value
   at System.Windows.Forms.ProgressBar.set_Value(Int32 value)
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.dlcGenerateButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by cozy1** [comment]
Try the latest toolkit beta.

**Comment by bacohen8** [comment]
Version: 2.8.2.0-93d25281 (32 bit)
 OS: Microsoft Windows NT 6.2.9200.0 (64 bit)
 Runtime: **v4.0.30319.42000**
 JIT: MsX86 

Input: H:\eof1.8RC10(r1337)\King Crimson - One Time\King Crimson One Time\.cache\Windows\SFX\One Time_4BF6154C.wem
Parse error: **unknown chunk type**


Still Crashes

**Comment by cozy1** [comment]
Are you converting ogg, or wav to wem?  Are you using toolkit to auto convert audio to wem, or are you preparing wem audio old fashion way with Wwise?  Could be you have a corrupt audio file.

**Comment by bacohen8** [comment]
I am converting using Wwise based on Youtube demos. It looks like you have conversion built into Song Creator. Ill give that a whirl.

**Comment by bacohen8** [comment]
Hey there! I'm Just checking back. Have you been able to re create the
issue? I anxious to contribute to the library.

**Comment by bacohen8** [comment]
Hi any Progress on this? I really want to get to work on this while I have
time.
