### ISSUE TITLE
Crash on import package

### ISSUE THREAD

**Issue by crackit2** [rscustom/rocksmith-custom-song-toolkit#326]
Hi,

this log is when I tried to import a package:

2018-10-01 18:10:13.6234 | RocksmithToolkitGUI.Program (INFO) : 
 RocksmithToolkitGUI.Program.Main 
 RocksmithToolkitGUI: v2.8.4.1-0209bb11 BETA
 RocksmithToolkitLib: v2.8.4.1-0209bb11 BETA
 RocksmithToolkitUpdater: v2.8.4.1-0209bb11 BETA
 Dynamic Difficulty Creator: v3.5
 OS: Microsoft Windows NT 6.1.7601 Service Pack 1 (64 bit)
 .NET Framework Runtime: v4.0.30319.42000
 JIT: MsX86
 Wine:  

2018-10-01 18:10:23.2962 | RocksmithToolkitGUI.Program (ERROR) : 
 RocksmithToolkitGUI.Program+<>c__DisplayClass1_0.<Main>b__1 
 
mscorlib
Void .ctor(Single)
Exception cached:

 
System.OverflowException Value was either too large or too small for a Decimal. Void .ctor(Single)    at System.Decimal..ctor(Single value)
   at System.Decimal.op_Explicit(Single value)
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.FillPackageCreatorForm(DLCPackageData info, String filesBaseDir)
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.PackageImport(String srcPath, String destDir)
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.btnPackageImport_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) System.OverflowException: Value was either too large or too small for a Decimal.
   at System.Decimal..ctor(Single value)
   at System.Decimal.op_Explicit(Single value)
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.FillPackageCreatorForm(DLCPackageData info, String filesBaseDir)
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.PackageImport(String srcPath, String destDir)
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.btnPackageImport_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by cozy1** [comment]
@crackit2 Always download and try the latest toolkit beta (test build) before reporting issues.  Let us know if latest beta solves your problem.  You will get faster response to questions like this on CF.

**Comment by crackit2** [comment]
The same is with latest best version...

**Comment by cozy1** [comment]
@crackit2 PM me on CF and provide a link to that song.  Also want latest toolkit log sent on CF.

**Comment by L0FKA** [comment]
wow much private suck close :D
