### ISSUE TITLE
Wwise audio file conversion failed: Unerwarteter Netzwerkfehler

### ISSUE THREAD

**Issue by M-w-N** [rscustom/rocksmith-custom-song-toolkit#347]
I get this error if i try to edit and save a psarc-file.
Other psarc have no problem.
Wwise v2013.2.10 build 4884 is installed.
What can i do?

``2020-05-17 04:00:44.4558 | RocksmithToolkitGUI.Program (INFO) : 
 RocksmithToolkitGUI.Program.Main 
  - RocksmithToolkitGUI: v2.9.2.1-0be6dc21
  - RocksmithToolkitLib: v2.9.2.1-0be6dc21 [27.02.2020 20:01:56]
  - RocksmithToolkitUpdater: v2.9.2.1-0be6dc21
  - Dynamic Difficulty Creator: v3.6
  - OS: Microsoft Windows NT 10.0.19559.0 (64 bit)
  - .NET Framework Runtime: v4.0.30319.42000
  - CultureInfo: (de-DE) 
  - Current Local DateTime: [17.05.2020 04:00:44]
  - Current UTC DateTime: [17.05.2020 02:00:44]
  - JIT: MsX86
  - WINE_INSTALLED: False
  - MacOSX: False  

2020-05-17 04:00:47.0198 | RocksmithToolkitGUI.Program (INFO) : 
 RocksmithToolkitGUI.MainForm.MainForm_Shown 
  - App.config Status (Load Successful)
  - System Display DPI Setting (96)
  - System Display Screen Scale Factor (125%) 
  - Adjusted AutoScaleDimensions, AutoScaleMode, and AutoSize 

2020-05-17 04:02:58.3965 | RocksmithToolkitGUI.Program (ERROR) : 
 RocksmithToolkitGUI.Program+<>c__DisplayClass0_0.<Main>b__1 
  - Application.ThreadException

Source: RocksmithToolkitLib
Target: Void Wav2Wem(System.String, System.String, Int32)
System.Exception: Wwise audio file conversion failed: Unerwarteter Netzwerkfehler.

   at RocksmithToolkitLib.Ogg.Wwise.Wav2Wem(String wavSourcePath, String destinationPath, Int32 audioQuality)
   at RocksmithToolkitLib.Ogg.OggFile.Convert2Wem(String audioPath, Int32 audioQuality, Int64 previewLength, Int64 chorusTime)
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.GetPackageData(Boolean validate, String& errorMsg)
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.PackageGenerate()
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.btnPackageGenerate_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) 
``

**Comment by M-w-N** [comment]
Problem is solved. ToolkitGUI was on a Network Drive, this makes the problem.

**Comment by L0FKA** [comment]
Well It may be due to policies that prevents toolkit from executing itself from network even if it's lan
so good for you but worth knowing what issue it was, thanks!
