### ISSUE TITLE
Sequence contains more than one matching element

### ISSUE THREAD

**Issue by Roabs** [rscustom/rocksmith-custom-song-toolkit#364]
When I try to generate the project, regardless of the file, it pops up an error: Sequence contains more than one matching element. I use version 2.9.2.1
![image](https://user-images.githubusercontent.com/33177829/107068358-ccb9dc80-67e0-11eb-86b2-1ee4f76f5f17.png)
2021-02-05` 18:31:27.1592 | RocksmithToolkitGUI.Program (INFO) : 
 RocksmithToolkitGUI.Program.Main 
  - RocksmithToolkitGUI: v2.9.2.1-a60453fa
  - RocksmithToolkitLib: v2.9.2.1-a60453fa [1/6/2021 8:45:10 PM]
  - RocksmithToolkitUpdater: v2.9.2.1-a60453fa
  - Dynamic Difficulty Creator: v3.6
  - OS: Microsoft Windows NT 10.0.19041.0 (64 bit)
  - .NET Framework Runtime: v4.0.30319.42000
  - CultureInfo: (en-US) 
  - Current Local DateTime: [2/5/2021 6:31:27 PM]
  - Current UTC DateTime: [2/5/2021 5:31:27 PM]
  - JIT: MsX86
  - WINE_INSTALLED: False
  - MacOSX: False  

2021-02-05 18:31:27.9827 | RocksmithToolkitGUI.Program (INFO) : 
 RocksmithToolkitGUI.MainForm.MainForm_Shown 
  - App.config Status (Load Successful)
  - System Display DPI Setting (96)
  - System Display Screen Scale Factor (100%)  

2021-02-05 18:31:29.2832 | RocksmithToolkitGUI.Program (ERROR) : 
 RocksmithToolkitGUI.Program+<>c__DisplayClass0_0.<Main>b__1 
  - Application.ThreadException

Source: System.Core
Target: TSource GetOneWithPossibleDefault[TSource](System.Linq.Parallel.QueryOperator`1[TSource], Boolean, Boolean)
System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ParallelEnumerable.GetOneWithPossibleDefault[TSource](QueryOperator`1 queryOp, Boolean throwIfTwo, Boolean defaultIfEmpty)
   at System.Linq.ParallelEnumerable.SingleOrDefault[TSource](ParallelQuery`1 source, Func`2 predicate)
   at RocksmithToolkitLib.Ogg.Wwise.GetWwisePath()
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.btnPackageGenerate_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) 

2021-02-05 18:33:29.9364 | RocksmithToolkitGUI.Program (ERROR) : 
 RocksmithToolkitGUI.Program+<>c__DisplayClass0_0.<Main>b__1 
  - Application.ThreadException

Source: System.Core
Target: TSource GetOneWithPossibleDefault[TSource](System.Linq.Parallel.QueryOperator`1[TSource], Boolean, Boolean)
System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ParallelEnumerable.GetOneWithPossibleDefault[TSource](QueryOperator`1 queryOp, Boolean throwIfTwo, Boolean defaultIfEmpty)
   at System.Linq.ParallelEnumerable.SingleOrDefault[TSource](ParallelQuery`1 source, Func`2 predicate)
   at RocksmithToolkitLib.Ogg.Wwise.GetWwisePath()
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.btnPackageGenerate_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by L0FKA** [comment]
Hello, It seems someting wrong with your wwise config, or you've got some weird edgecase bug? please let me know what wwise version you've got and show me screenshot of your config window, main issue here is it trying to get wwise exe path and has controversy what to return as such

**Comment by Roabs** [comment]
Yes thank you but I managed to fix it. I had the wrong version of wwise (2019.2 I think) so I installed the 2013 version and now it works
