### ISSUE TITLE
reporting a crash

### ISSUE THREAD

**Issue by bobbobbin** [rscustom/rocksmith-custom-song-toolkit#375]
Hi,
when trying to load a file, the toolkit asked me to send the LOG file to you.
the file plays in rocksmith 2014, but when trying to edit it...

Application.ThreadException:
Invalid Package

2022-07-14 15:58:04.5098 | RocksmithToolkitGUI.Program (INFO) : 
 RocksmithToolkitGUI.Program.Main 
  - RocksmithToolkitGUI: v2.9.2.1-5df928a5
  - RocksmithToolkitLib: v2.9.2.1-5df928a5 [09-Oct-21 6:22:52 PM]
  - RocksmithToolkitUpdater: v2.9.2.1-5df928a5
  - Dynamic Difficulty Creator: v3.6
  - OS: Microsoft Windows NT 10.0.22000.0 (64 bit)
  - .NET Framework Runtime: v4.0.30319.42000
  - CultureInfo: (en-US) 
  - Current Local DateTime: [14-Jul-22 3:58:04 PM]
  - Current UTC DateTime: [14-Jul-22 10:58:04 PM]
  - JIT: MsX86
  - WINE_INSTALLED: False
  - MacOSX: False  

2022-07-14 15:58:05.0068 | RocksmithToolkitGUI.Program (INFO) : 
 RocksmithToolkitGUI.MainForm.MainForm_Shown 
  - App.config Status (Load Successful)
  - System Display DPI Setting (96)
  - System Display Screen Scale Factor (150%) 
  - Adjusted AutoScaleDimensions, AutoScaleMode, and AutoSize 

2022-07-14 16:11:10.0056 | RocksmithToolkitGUI.Program (ERROR) : 
 RocksmithToolkitGUI.Program+<>c__DisplayClass0_0.<Main>b__1 
  - Application.ThreadException

Source: X360
Target: Void .ctor(X360.IO.DJsIO, X360.Other.LogRecord)
System.Exception: Invalid Package
   at X360.STFS.STFSPackage..ctor(DJsIO xIOIn, LogRecord LogIn)
   at RocksmithToolkitLib.DLCPackage.Packer.UnpackXBox360Package(String srcPath, String destDirPath, Platform platform)
   at RocksmithToolkitLib.DLCPackage.Packer.Unpack(String srcPath, String destDirPath, Platform overridePlatform, Boolean decodeAudio, Boolean overwriteSongXml)
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.PackageImport(String srcPath, String destDir)
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.btnPackageImport_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) 

2022-07-14 20:44:45.4291 | RocksmithToolkitGUI.Program (ERROR) : 
 RocksmithToolkitGUI.Program+<>c__DisplayClass0_0.<Main>b__1 
  - Application.ThreadException

Source: X360
Target: Void .ctor(X360.IO.DJsIO, X360.Other.LogRecord)
System.Exception: Invalid Package
   at X360.STFS.STFSPackage..ctor(DJsIO xIOIn, LogRecord LogIn)
   at RocksmithToolkitLib.DLCPackage.Packer.UnpackXBox360Package(String srcPath, String destDirPath, Platform platform)
   at RocksmithToolkitLib.DLCPackage.Packer.Unpack(String srcPath, String destDirPath, Platform overridePlatform, Boolean decodeAudio, Boolean overwriteSongXml)
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.PackageImport(String srcPath, String destDir)
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.btnPackageImport_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by L0FKA** [comment]
It seems to be an issue with file you're trying to import? Is it xbox cdlc file you need to edit? If it's mac or pc with short filename toolkit can misjudge it as xbox file(just rename it to be something longer than 10 symbols) If it's really xbox cdlc join our discord of post a link to the file so I could try to reproduce this error myself ✌️🙂

**Comment by bobbobbin** [comment]
hi! thanks for your reply. You know, I did rename it, as you suggested - and now it opens fine in toolkit and saves just fine! ha, that was an easy fix - it never occured to me to try that! thanks very much! if i run in to another file that hiccups like this, i'll try renaming it. cheers!
