### ISSUE TITLE
fail to convert vocal sng to xml

### ISSUE THREAD

**Issue by bobbobbin** [rscustom/rocksmith-custom-song-toolkit#377]
hi, here is the LOG file, TIA! [rocksmith 2014 remastered]
2022-08-30 02:38:53.8180 | RocksmithToolkitGUI.Program (INFO) : 
 RocksmithToolkitGUI.Program.Main 
  - RocksmithToolkitGUI: v2.9.2.1-5df928a5
  - RocksmithToolkitLib: v2.9.2.1-5df928a5 [09-Oct-21 6:22:52 PM]
  - RocksmithToolkitUpdater: v2.9.2.1-5df928a5
  - Dynamic Difficulty Creator: v3.6
  - OS: Microsoft Windows NT 10.0.22000.0 (64 bit)
  - .NET Framework Runtime: v4.0.30319.42000
  - CultureInfo: (en-US) 
  - Current Local DateTime: [30-Aug-22 2:38:53 AM]
  - Current UTC DateTime: [30-Aug-22 9:38:53 AM]
  - JIT: MsX86
  - WINE_INSTALLED: False
  - MacOSX: False  

2022-08-30 02:38:55.1584 | RocksmithToolkitGUI.Program (INFO) : 
 RocksmithToolkitGUI.MainForm.MainForm_Shown 
  - App.config Status (Load Successful)
  - System Display DPI Setting (96)
  - System Display Screen Scale Factor (125%) 
  - Adjusted AutoScaleDimensions, AutoScaleMode, and AutoSize 

2022-08-30 16:15:03.9643 | RocksmithToolkitGUI.Program (ERROR) : 
 RocksmithToolkitGUI.Program+<>c__DisplayClass0_0.<Main>b__1 
  - Application.ThreadException

Source: System.Xml
Target: Void Throw(System.Exception)
System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.MoveToContent()
   at RocksmithToolkitLib.XML.Song2014.DetectArrangementType(String xmlFile)
   at RocksmithToolkitGUI.DLCPackageCreator.ArrangementForm.AddXmlArrangement(String xmlFilePath)
   at RocksmithToolkitGUI.DLCPackageCreator.ArrangementForm.btnBrowseXml_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) 

2022-08-30 16:15:18.4979 | RocksmithToolkitGUI.Program (ERROR) : 
 RocksmithToolkitGUI.Program+<>c__DisplayClass0_0.<Main>b__1 
  - Application.ThreadException

Source: System.Xml
Target: Void Throw(System.Exception)
System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.MoveToContent()
   at RocksmithToolkitLib.XML.Song2014.DetectArrangementType(String xmlFile)
   at RocksmithToolkitGUI.DLCPackageCreator.ArrangementForm.AddXmlArrangement(String xmlFilePath)
   at RocksmithToolkitGUI.DLCPackageCreator.ArrangementForm.btnBrowseXml_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) 

2022-08-30 22:26:55.6633 | RocksmithToolkitGUI.Program (ERROR) : 
 RocksmithToolkitGUI.Program+<>c__DisplayClass0_0.<Main>b__1 
  - Application.ThreadException

Source: mscorlib
Target: Void ThrowInvalidOperationException(System.ExceptionResource)
System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at RocksmithToolkitLib.XML.Song2014..ctor(Sng sngData, Attributes2014 attr)
   at RocksmithToolkitGUI.SngConverter.SngConverter.convertSngXmlButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) 

2022-08-30 22:31:46.4258 | RocksmithToolkitGUI.Program (ERROR) : 
 RocksmithToolkitGUI.Program+<>c__DisplayClass0_0.<Main>b__1 
  - Application.ThreadException

Source: RocksmithToolkitLib
Target: Void DecryptSngData(System.IO.Stream, System.IO.Stream, Byte[], MiscUtil.Conversion.EndianBitConverter)
System.IO.InvalidDataException: This is not valid SNG file to decrypt.
   at RocksmithToolkitLib.DLCPackage.RijndaelEncryptor.DecryptSngData(Stream input, Stream output, Byte[] key, EndianBitConverter conv)
   at RocksmithToolkitLib.Sng2014HSL.Sng2014File.UnpackSng(Stream input, Stream output, Platform platform)
   at RocksmithToolkitLib.Sng2014HSL.Sng2014File.ReadSng(Stream input, Platform platform)
   at RocksmithToolkitLib.Sng2014HSL.Sng2014File.LoadFromFile(String inputFile, Platform platform)
   at RocksmithToolkitGUI.SngConverter.SngConverter.convertSngXmlButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) 

2022-08-30 22:34:07.4655 | RocksmithToolkitGUI.Program (ERROR) : 
 RocksmithToolkitGUI.Program+<>c__DisplayClass0_0.<Main>b__1 
  - Application.ThreadException

Source: mscorlib
Target: Void ThrowInvalidOperationException(System.ExceptionResource)
System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at RocksmithToolkitLib.XML.Song2014..ctor(Sng sngData, Attributes2014 attr)
   at RocksmithToolkitGUI.SngConverter.SngConverter.convertSngXmlButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) 

2022-08-30 22:39:54.3767 | RocksmithToolkitGUI.Program (ERROR) : 
 RocksmithToolkitGUI.Program+<>c__DisplayClass0_0.<Main>b__1 
  - Application.ThreadException

Source: mscorlib
Target: Void ThrowInvalidOperationException(System.ExceptionResource)
System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at RocksmithToolkitLib.XML.Song2014..ctor(Sng sngData, Attributes2014 attr)
   at RocksmithToolkitGUI.SngConverter.SngConverter.convertSngXmlButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) 

2022-08-30 22:48:33.3821 | RocksmithToolkitGUI.Program (ERROR) : 
 RocksmithToolkitGUI.Program+<>c__DisplayClass0_0.<Main>b__1 
  - Application.ThreadException

Source: System.Xml
Target: Void Throw(System.Exception)
System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.MoveToContent()
   at RocksmithToolkitLib.XML.Song2014.DetectArrangementType(String xmlFile)
   at RocksmithToolkitGUI.DLCPackageCreator.ArrangementForm.AddXmlArrangement(String xmlFilePath)
   at RocksmithToolkitGUI.DLCPackageCreator.ArrangementForm.btnBrowseXml_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) 

2022-08-30 22:52:45.3861 | RocksmithToolkitGUI.Program (ERROR) : 
 RocksmithToolkitGUI.Program+<>c__DisplayClass0_0.<Main>b__1 
  - Application.ThreadException

Source: mscorlib
Target: Void ThrowInvalidOperationException(System.ExceptionResource)
System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at RocksmithToolkitLib.XML.Song2014..ctor(Sng sngData, Attributes2014 attr)
   at RocksmithToolkitGUI.SngConverter.SngConverter.convertSngXmlButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by L0FKA** [comment]
I assume sng file us missing some data or empty, could be an issue to detect platform or really malformed file fed, I think you're trying to convert to another platform? please provide additional details at minimum .sng file so I could validate it's good or bad or is it toolkit's issue🙂

**Comment by bobbobbin** [comment]
Hi,

 

Please find attached one of the SNG files, cheers.

 

It’s one of 6 ones that fail to convert to an XML file.

 

Thanks!

 

Kindest regards,

 

Deron

**Comment by L0FKA** [comment]
Please attach files directly on github issues page or via email to ul0fka(at)gmail.com

p.s. you've just sent those files to github notification  bot not me.😅
