### ISSUE TITLE
Error::The directory name is invalid.

### ISSUE THREAD

**Issue by Carlonjumala** [rscustom/rocksmith-custom-song-toolkit#382]
![image](https://github.com/rscustom/rocksmith-custom-song-toolkit/assets/73998093/8e438584-a816-47b4-bd2e-c3e1755665b0)

The logs file gives the following:

2023-07-01 21:09:49.2523 | RocksmithToolkitGUI.Program (INFO) : 
 RocksmithToolkitGUI.Program.Main 
  - RocksmithToolkitGUI: v2.9.2.1-5df928a5
  - RocksmithToolkitLib: v2.9.2.1-5df928a5 [09/10/2021 18.22.52]
  - RocksmithToolkitUpdater: v2.9.2.1-5df928a5
  - Dynamic Difficulty Creator: v3.6
  - OS: Microsoft Windows NT 10.0.19045.0 (64 bit)
  - .NET Framework Runtime: v4.0.30319.42000
  - CultureInfo: (en-FI) 
  - Current Local DateTime: [01/07/2023 21.09.49]
  - Current UTC DateTime: [01/07/2023 18.09.49]
  - JIT: MsX86
  - WINE_INSTALLED: False
  - MacOSX: False  

2023-07-01 21:09:50.1170 | RocksmithToolkitGUI.Program (INFO) : 
 RocksmithToolkitGUI.MainForm.MainForm_Shown 
  - App.config Status (Load Successful)
  - System Display DPI Setting (96)
  - System Display Screen Scale Factor (100%)  

2023-07-01 21:09:57.0247 | RocksmithToolkitGUI.Program (ERROR) : 
 RocksmithToolkitGUI.Program+<>c__DisplayClass0_0.<Main>b__1 
  - Application.ThreadException

Source: mscorlib
Target: Void WinIOError(Int32, System.String)
System.IO.IOException: The directory name is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern, SearchOption searchOption)
   at RocksmithToolkitLib.Ogg.Wwise.GetWwisePath()
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.btnPackageGenerate_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) 

This happens when I'm trying to convert Rocksmith song  to Rocksmith 2014 edition.

**Comment by L0FKA** [comment]
Hello, It seems like you've got no wwise 2013 installed or your rs1 song is actually official dlc of sorts? It also could be culture related issue but it's unlikely here.
